version: 2 # use CircleCI 2.0
jobs:  # a collection of steps
  build:
    docker: # run the steps with Docker
      - image: circleci/node:7.10
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: Install packages with NPM
          command: npm install
      - run:
          name: Build the app with NPM
          command: npm run build
      - run:
        name: Deploy the "master" branch to Heroku git push force
        command: |
          git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  # deploy:
  #   docker:
  #     - image: buildpack-deps
  #   steps:
  #     - checkout
     
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      # - deploy:
      #     requires:
      #       - build
